info:
    app:
        description: Master Spring Boot
        name: Spring Boot Master Class Course
        version: 1.0.0
    company:
        name: Amigoscode
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: health,info,prometheus
server:
    error:
        include-binding-errors: always
        include-message: always
        include-stacktrace: on_trace_param
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: hello
        url: jdbc:h2:mem:testdb-dev-environment
        username: hello
    h2:
        console:
            enabled: true
            path: /h2-dev
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
    main:
        banner-mode: 'off'
